<div class="row">
        <div class="col-md-6">
            <h2>
                <?=$this->content[0]['name']?>
            </h2>
           
                
                    <p>
                        <?=$this->content[0]['text']?>
                    </p>

            <h2>
                <a href="../../tag/view/<?= $this->content[0]['tags_id']; ?>"><?= $this->content[0]['tag']; ?></a>
            </h2>

        </div>

</div>


